In [83]:
import numpy as np

data = [[1, 1, 0, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 0, 1, 1]]
alpha = 0.6
beta = 0.5
epoch = 0
maxEpoch = 1

weight = [[0.2, 0.6, 0.5, 0.9],
          [0.8, 0.4, 0.7, 0.3]]


np_data = np.array(data)
np_weight = np.array(weight)


while epoch < maxEpoch:
    print("------------------------- Epoch ke", epoch+1,"--------------------------------")
    for x in np_data:
        euclidianDistance = [sum((w - x) ** 2) for w in np_weight]
        print("============= Euclidian Distance ================")
        print("")
        print(euclidianDistance)
        print("")
        print("Euclidian Distance 1:",euclidianDistance[0])
        print("Euclidian Distance 2:", euclidianDistance[1])

        print("")
        print("============= Jarak terdekat dari Euclidian Distance ==============")
        print("")
        if euclidianDistance[0] <= euclidianDistance[1]:
            print("pemenang = ",euclidianDistance[0])
            print("")
            print("=========== Update Bobot ============")
            np_weight[0] += alpha * (x - np_weight[0])
            print(np_weight)
        else:
            print("pemenang = ",euclidianDistance[1])
            print("")
            print("=========== Update Bobot ============")
            np_weight[1] += alpha * (x - np_weight[1])
            print(np_weight)
            
        print("")
        
    alpha *= beta
    epoch +=1

dataTest = [[0.1, 0.2, 0.3, 0.4],
            [0.5, 0.6, 0.7, 0.8],
            [0.9, 0.10, 0.11, 0.12]]
print("------------------ Testing ------------------")
cluster1 = []
cluster2 = []
for xTest in dataTest:
    testing = [sum((weightTesting - xTest) ** 2) for weightTesting in np_weight]
    print("Euclidian Distance 1:",testing[0])
    print("Euclidian Distance 2",testing[1])
    print("")
    print("--------------- Pemenang --------------")
    if testing[0] <= testing[1]:
        print("pemenang =", testing[0],"termasuk cluster 1")
        cluster1.append(testing[0])
        
    else:
        print("pemenang =", testing[1],"termasuk cluster 2")
        cluster2.append(testing[1])
    print("===============================")
    print("")
    print("---------------------Hasil cluster --------------------------")
    print("cluster 1: ", cluster1)
    print("cluster 2: ", cluster2)

------------------------- Epoch ke 1 --------------------------------
============= Euclidian Distance ================

[1.8600000000000003, 0.9799999999999999]

Euclidian Distance 1: 1.8600000000000003
Euclidian Distance 2: 0.9799999999999999

============= Jarak terdekat dari Euclidian Distance ==============

pemenang =  0.9799999999999999

=========== Update Bobot ============
[[0.2  0.6  0.5  0.9 ]
 [0.92 0.76 0.28 0.12]]

============= Euclidian Distance ================

[0.66, 2.2767999999999997]

Euclidian Distance 1: 0.66
Euclidian Distance 2: 2.2767999999999997

============= Jarak terdekat dari Euclidian Distance ==============

pemenang =  0.66

=========== Update Bobot ============
[[0.08 0.24 0.2  0.96]
 [0.92 0.76 0.28 0.12]]

============= Euclidian Distance ================

[1.8655999999999997, 0.6768]

Euclidian Distance 1: 1.8655999999999997
Euclidian Distance 2: 0.6768

============= Jarak terdekat dari Euclidian Distance ==============

pemenang =  0.6768

=====

In [58]:
A = 0.5
B = 0.6
C = [0.5,.6]

chasil = np.array(C)
minimum=np.argmin(chasil)
print(minimum)

if A <= B:
    print("pemenang = ",A)
else:
    print("pemenang = ",B)

0
pemenang =  0.5


In [36]:
import numpy as np

data = [[1, 1, 0, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 0, 1, 1]]
alpha = 0.6
beta = 0.5
epoch = 0
maxEpoch = 1

weight = [[0.2, 0.6, 0.5, 0.9],
          [0.8, 0.4, 0.7, 0.3]]

np_data = np.array(data)
np_weight = np.array(weight)

while epoch < maxEpoch:
    for x in np_data:
        euclidianDistance = [sum((w - x) ** 2) for w in np_weight]
        minimum = np.argmin(euclidianDistance)
        np_weight[minimum] += alpha * (x - np_weight[minimum])
        print(np_weight)
    alpha *= beta
    epoch +=1

dataTest = [[0.1, 0.2, 0.3, 0.4],
            [0.5, 0.6, 0.7, 0.8],
            [0.9, 0.10, 0.11, 0.12]]
for xTest in dataTest:
    testing = [sum((weightTesting - xTest) ** 2) for weightTesting in np_weight]
    minimumTesting = np.argmin(testing)
    print("===============Testing================")
    print(testing[minimumTesting])

[[0.2  0.6  0.5  0.9 ]
 [0.92 0.76 0.28 0.12]]
[[0.08 0.24 0.2  0.96]
 [0.92 0.76 0.28 0.12]]
[[0.08  0.24  0.2   0.96 ]
 [0.968 0.304 0.112 0.048]]
[[0.032 0.096 0.68  0.984]
 [0.968 0.304 0.112 0.048]]
===============Testing================
0.500896
===============Testing================
0.507296
===============Testing================
0.051428
